:wikitext: https://wiki.eclipse.org/Mylyn/WikiText
:bug421551: https://bugs.eclipse.org/bugs/show_bug.cgi?id=421551
:mylyn_ml: http://dev.eclipse.org/mhonarc/lists/mylyn-docs-dev/
:mylyn_forum: http://www.eclipse.org/forums/index.php/f/83/
:mylyn_so: http://stackoverflow.com/tags/mylyn-wikitext
:bintray_package: https://bintray.com/jmini/maven/mylyn-wikitext/view
:eclipse_b3: https://www.eclipse.org/b3
:githubrepo: jmini/mylyn-wikitext-repository
:issues: https://github.com/{githubrepo}/issues
:license: http://www.eclipse.org/legal/epl-v10.html
:oomph_file: MylynWikitextRepository.setup
:oomph_setup: https://raw.githubusercontent.com/{githubrepo}/master/{oomph_file}
:blog-post: https://jmini.github.io/blog/2016/2016-02-21_maven_repo_and_pom_files.html


= mylyn-wikitext-repository

This repository contains my notes and tools to create a maven repository for the link:{wikitext}[Mylyn Wikitext] jars.
This is a workaround for link:{bug421551}[Bug 421551].

== Usage

You can use Mylyn Wikitext jars (browse them in the link:{bintray_package}[mylyn-wikitext package]) from my maven repository hosted on bintray:

  http://dl.bintray.com/jmini/maven/

To use the Mylyn Wikitext jars in your pom, pick the interesting parts in from this snippet:

[source,xml]
----
<project>
  <!-- ... -->
  <dependencies>
    <dependency>
      <groupId>org.eclipse.mylyn.docs</groupId>
      <artifactId>org.eclipse.mylyn.wikitext.asciidoc.core</artifactId>
      <version>2.9.0.v20160524-1633</version>
    </dependency>
    <dependency>
      <groupId>org.eclipse.mylyn.docs</groupId>
      <artifactId>org.eclipse.mylyn.wikitext.confluence.core</artifactId>
      <version>2.9.0.v20160513-1433</version>
    </dependency>
    <dependency>
      <groupId>org.eclipse.mylyn.docs</groupId>
      <artifactId>org.eclipse.mylyn.wikitext.core</artifactId>
      <version>2.9.0.v20160513-1433</version>
    </dependency>
    <dependency>
      <groupId>org.eclipse.mylyn.docs</groupId>
      <artifactId>org.eclipse.mylyn.wikitext.core.ant</artifactId>
      <version>2.9.0.v20160513-1433</version>
    </dependency>
    <dependency>
      <groupId>org.eclipse.mylyn.docs</groupId>
      <artifactId>org.eclipse.mylyn.wikitext.html.core</artifactId>
      <version>2.9.0.v20160513-1433</version>
    </dependency>
    <dependency>
      <groupId>org.eclipse.mylyn.docs</groupId>
      <artifactId>org.eclipse.mylyn.wikitext.markdown.core</artifactId>
      <version>2.9.0.v20160513-1433</version>
    </dependency>
    <dependency>
      <groupId>org.eclipse.mylyn.docs</groupId>
      <artifactId>org.eclipse.mylyn.wikitext.mediawiki.core</artifactId>
      <version>2.9.0.v20160513-1433</version>
    </dependency>
    <dependency>
      <groupId>org.eclipse.mylyn.docs</groupId>
      <artifactId>org.eclipse.mylyn.wikitext.mediawiki.core.ant</artifactId>
      <version>2.9.0.v20160513-1433</version>
    </dependency>
    <dependency>
      <groupId>org.eclipse.mylyn.docs</groupId>
      <artifactId>org.eclipse.mylyn.wikitext.textile.core</artifactId>
      <version>2.9.0.v20160513-1433</version>
    </dependency>
    <dependency>
      <groupId>org.eclipse.mylyn.docs</groupId>
      <artifactId>org.eclipse.mylyn.wikitext.tracwiki.core</artifactId>
      <version>2.9.0.v20160513-1433</version>
    </dependency>
    <dependency>
      <groupId>org.eclipse.mylyn.docs</groupId>
      <artifactId>org.eclipse.mylyn.wikitext.twiki.core</artifactId>
      <version>2.9.0.v20160519-0832</version>
    </dependency>

  </dependencies>
  
  <repositories>
    <repository>
      <id>bintray.jmini.maven</id>
      <url>http://dl.bintray.com/jmini/maven/</url>
    </repository>
  </repositories>
</project>
----

A simple example (pom file and simple java class) is presented in this link:{blog-post}[blog post].

=== Versions

* link:https://bintray.com/jmini/maven/mylyn-wikitext/Mars.0/view[Mars.0] (24/06/2015), Version `2.5.0.v*`
* link:https://bintray.com/jmini/maven/mylyn-wikitext/Mars.1/view[Mars.1] (02/10/2015), Version `2.6.0.v*`
* link:https://bintray.com/jmini/maven/mylyn-wikitext/Mars.2/view[Mars.2] (26/02/2016), Version `2.7.0.v*`
* link:https://bintray.com/jmini/maven/mylyn-wikitext/Neon.0/view[Neon.0] (22/06/2016), Version `2.9.0.v*`


=== Remarks
Because the Idea of this repository is to consume mylyn-wikitext in a plain maven project (or maven plugin), only the `core` jars are published.
In my opinion the `ui` jars are consumed in an Eclipse RCP context where building with Tycho and consuming the P2 repository is not a problem.

The Eclipse simultaneous release train (starting with `Mars.0`) was used as base to build the maven repository.
This is why a jar like `org.eclipse.mylyn.wikitext.commonmark` is not available in the repository.

=== Examples

Check out the link:examples/[examples].

=== Setup in Eclipse IDE

There is an Eclipse Oomph Setup Task to import this project: link:{oomph_setup}[{oomph_file}]


== Official maven repository

The Mylyn Wikitext project provides an official maven repository hosted by the Eclipse fundation:

  https://repo.eclipse.org/content/repositories/mylyn-snapshots/

Please note that this repository contains only snapshot artifacts.
A major difference is also that link:{blog-post}[the dependencies declaration is not the same between the Eclipse Fundation repository and my repository].
I consider my repository as much more user friendly.

== Issue tracker / Get in touch

For this project (content of this repository and of the maven repository):

* Use the link:{issues}[mylyn-wikitext-repository issue tracker] on GitHub.

For the `mylyn-wikitext` project itself:

* Mailing list: link:{mylyn_ml}[mylyn-docs-dev]
* Forum: link:{mylyn_forum}[Mylyn]
* StackOverflow Tag: link:{mylyn_so}[mylyn-wikitext]

== Notes

=== Description

I have used the link:{eclipse_b3}[Eclipse b3] tool to convert the p2 repository into a maven repository.
The `*.b3aggr` files are located in the `aggregator` project.

Some help scripts written in Java are located in the `javatools` project.

=== Build

There is no automatic build at the moment.
This section describes the manual steps requested to build the maven repository and to upload it to bintray.

. Open an `*.b3aggr` file with the "Aggregator Model Editor".
. Select the root node and run "Build Aggregation".
. In the created repository, the p2 files are not necessary:
  * {repository}/final/artifacts.jar
  * {repository}/final/content.jar
  * {repository}/final/p2.index
  * ..
. Zip the interesting parts of the "{repository}/final" folder. You should use the `default` Ant task provided in the `build.xml` file to do this.
. Upload this zip to bintray. To use the web UI, a version should exists in a package.


== License

link:{license}[Eclipse Public License - v 1.0]
